name: Cross-platform Nuitka Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install nuitka==1.8.6
        python -m nuitka --version

    - name: Build with Nuitka
      run: |
        mkdir build_output
        python -m nuitka --standalone main.py --output-dir=build_output --name=backup_key_manager

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: backup_key_manager-${{ matrix.os }}
        path: |
          build_output/backup_key_manager-${{ matrix.os }}/backup_key_manager
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build_output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build_output/backup_key_manager-ubuntu-latest/backup_key_manager
            build_output/backup_key_manager-windows-latest/backup_key_manager.exe
            build_output/backup_key_manager-macos-latest/backup_key_manager
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

