name: Build USB-Compatible App with Nuitka

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      NUITKA_CCACHE_BINARY: ""  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build with Nuitka (standalone)
      shell: bash
      run: |
        mkdir build_output
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          nuitka --standalone main.py --output-dir=build_output --output-filename=usb_tool.exe
        else
          nuitka --standalone main.py --output-dir=build_output --output-filename=usb_tool
        fi

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build_output/usb_tool*
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          USB Backup Manager ${{ github.ref_name }}
          
          Download the appropriate binary for your system:
          - Windows: usb_tool.exe
          - macOS/Linux: usb_tool
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
