name: USB Backup Key Manager Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      NUITKA_CCACHE_BINARY: ""  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build with Nuitka (standalone)
      run: |
        mkdir build_output
        nuitka --standalone main.py --assume-yes-for-downloads --output-dir=build_output --output-filename=backup_key_manager

    - name: Upload output folder
      uses: actions/upload-artifact@v4
      with:
        name: backup_key_manager-${{ matrix.os }}
        path: build_output/backup_key_manager.dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build_output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build_output/backup_key_manager-ubuntu-latest/backup_key_manager.dist/backup_key_manager
            build_output/backup_key_manager-windows-latest/backup_key_manager.dist/backup_key_manager.exe
            build_output/backup_key_manager-macos-latest/backup_key_manager.dist/backup_key_manager
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

